// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getBootstrapSnapshot: () => typedError<BootstrapSnapshotDto, ApiError>(__TAURI_INVOKE("get_bootstrap_snapshot")),
	refreshBootstrapSnapshot: () => typedError<BootstrapSnapshotDto, ApiError>(__TAURI_INVOKE("refresh_bootstrap_snapshot")),
	getDashboardSnapshot: () => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("get_dashboard_snapshot")),
	refreshDashboardSnapshot: () => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("refresh_dashboard_snapshot")),
	setGpuMode: (request: SetGpuModeRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_gpu_mode", { request })),
	setPowerProfile: (request: SetPowerProfileRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_power_profile", { request })),
	setPlatformProfile: (request: SetPlatformProfileRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_platform_profile", { request })),
	nextPlatformProfile: () => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("next_platform_profile")),
	setChargeLimit: (request: SetChargeLimitRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_charge_limit", { request })),
	batteryOneShotCharge: (request: BatteryOneShotRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("battery_one_shot_charge", { request })),
	readFanCurves: (request: ReadFanCurvesRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("read_fan_curves", { request })),
	resetFanCurves: (request: ResetFanCurvesRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("reset_fan_curves", { request })),
	setFanCurvesEnabled: (request: SetFanCurvesEnabledRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_fan_curves_enabled", { request })),
	setFanCurve: (request: SetFanCurveRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_fan_curve", { request })),
	setAuraBrightness: (request: SetAuraBrightnessRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_aura_brightness", { request })),
	setAuraMode: (request: SetAuraModeRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_aura_mode", { request })),
	setLedsBrightness: (request: SetLedsBrightnessRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_leds_brightness", { request })),
	nextLedsBrightness: () => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("next_leds_brightness")),
	prevLedsBrightness: () => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("prev_leds_brightness")),
	setAnimeDisplayEnabled: (request: SetAnimeDisplayEnabledRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_anime_display_enabled", { request })),
	setAnimeBrightness: (request: SetAnimeBrightnessRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_anime_brightness", { request })),
	setAnimeBuiltinsEnabled: (request: SetAnimeBuiltinsEnabledRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_anime_builtins_enabled", { request })),
	setAnimeOffWhenLidClosed: (request: SetAnimeOffConditionRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_anime_off_when_lid_closed", { request })),
	setAnimeOffWhenSuspended: (request: SetAnimeOffConditionRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_anime_off_when_suspended", { request })),
	setAnimeOffWhenUnplugged: (request: SetAnimeOffConditionRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_anime_off_when_unplugged", { request })),
	setSlashEnabled: (request: SetSlashEnabledRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_enabled", { request })),
	setSlashBrightness: (request: SetSlashBrightnessRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_brightness", { request })),
	setSlashInterval: (request: SetSlashIntervalRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_interval", { request })),
	setSlashMode: (request: SetSlashModeRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_mode", { request })),
	setSlashShowOnBoot: (request: SetSlashFlagRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_show_on_boot", { request })),
	setSlashShowOnShutdown: (request: SetSlashFlagRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_show_on_shutdown", { request })),
	setSlashShowOnSleep: (request: SetSlashFlagRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_show_on_sleep", { request })),
	setSlashShowOnBattery: (request: SetSlashFlagRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_show_on_battery", { request })),
	setSlashShowBatteryWarning: (request: SetSlashFlagRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_show_battery_warning", { request })),
	setSlashShowOnLidClosed: (request: SetSlashFlagRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_slash_show_on_lid_closed", { request })),
	setBacklight: (request: SetBacklightRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_backlight", { request })),
	readBacklightSnapshot: () => typedError<BacklightStatusSnapshot, ApiError>(__TAURI_INVOKE("read_backlight_snapshot")),
	setScsiEnabled: (request: SetScsiEnabledRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_scsi_enabled", { request })),
	setScsiMode: (request: SetScsiModeRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_scsi_mode", { request })),
	readScsiSnapshot: () => typedError<ScsiStatusSnapshot, ApiError>(__TAURI_INVOKE("read_scsi_snapshot")),
	setArmouryValue: (request: SetArmouryValueRequest) => typedError<DashboardSnapshotDto, ApiError>(__TAURI_INVOKE("set_armoury_value", { request })),
};

/* Types */
export type AnimeStatusSnapshot = {
	enableDisplay: boolean | null,
	builtinsEnabled: boolean | null,
	brightness: string | null,
	offWhenLidClosed: boolean | null,
	offWhenSuspended: boolean | null,
	offWhenUnplugged: boolean | null,
	lastError: string | null,
};

export type ApiError = {
	code: string,
	message: string,
};

export type ArmouryAttributeSnapshot = {
	path: string,
	name: string | null,
	availableAttrs: string | null,
	currentValue: number | null,
	defaultValue: number | null,
	minValue: number | null,
	maxValue: number | null,
	possibleValues: string | null,
	scalarIncrement: number | null,
	queuedGpuValue: number | null,
	lastError: string | null,
};

export type ArmouryStatusSnapshot = {
	attributes: ArmouryAttributeSnapshot[],
	lastError: string | null,
};

export type AuraStatusSnapshot = {
	brightness: string | null,
	ledMode: string | null,
	supportedBrightness: string | null,
	supportedBasicModes: string | null,
	lastError: string | null,
};

export type BacklightStatusSnapshot = {
	screenpadBrightness: number | null,
	screenpadGamma: string | null,
	syncScreenpadBrightness: boolean | null,
	lastError: string | null,
};

export type BatteryOneShotRequest = {
	percent: number | null,
};

export type BootstrapSnapshotDto = {
	health: DaemonHealthSnapshot,
};

export type CpuPerformanceSnapshot = {
	frequencyMhz: number | null,
	utilizationPercent: number | null,
	coreCount: number | null,
	lastError: string | null,
};

export type DaemonHealthSnapshot = {
	asusdAvailable: boolean,
	supergfxdAvailable: boolean,
	ppdAvailable: boolean,
	lastError: string | null,
};

export type DaemonInterfaceSnapshot = {
	asusdPlatformAvailable: boolean,
	asusdFanCurvesAvailable: boolean,
	asusdAuraAvailable: boolean,
	asusdAnimeAvailable: boolean,
	asusdSlashAvailable: boolean,
	asusdScsiAvailable: boolean,
	asusdBacklightAvailable: boolean,
	asusdArmouryAvailable: boolean,
	supergfxdInterfaceAvailable: boolean,
	ppdInterfaceAvailable: boolean,
};

export type DashboardSnapshotDto = {
	health: DaemonHealthSnapshot,
	interfaces: DaemonInterfaceSnapshot,
	performance: PerformanceSnapshot,
	gpu: GpuStatusSnapshot,
	power: PowerStatusSnapshot,
	platform: PlatformStatusSnapshot,
	fanCurves: FanCurvesStatusSnapshot,
	aura: AuraStatusSnapshot,
	anime: AnimeStatusSnapshot,
	slash: SlashStatusSnapshot,
	scsi: ScsiStatusSnapshot,
	backlight: BacklightStatusSnapshot,
	armoury: ArmouryStatusSnapshot,
	updatedAtMs: number,
};

export type FanCurvePointSnapshot = {
	temperature: number,
	pwm: number,
};

export type FanCurveSeriesSnapshot = {
	fan: string,
	enabled: boolean,
	points: FanCurvePointSnapshot[],
};

export type FanCurvesStatusSnapshot = {
	activeProfile: string | null,
	profileChoices: string | null,
	curveData: string | null,
	curveSeries: FanCurveSeriesSnapshot[],
	lastError: string | null,
};

export type GpuPerformanceSnapshot = {
	frequencyMhz: number | null,
	utilizationPercent: number | null,
	source: string | null,
	lastError: string | null,
};

export type GpuStatusSnapshot = {
	mode: string | null,
	power: string | null,
	pendingMode: string | null,
	pendingAction: string | null,
	daemonVersion: string | null,
	vendor: string | null,
	supportedModes: string | null,
	lastError: string | null,
};

export type PerformanceSnapshot = {
	cpu: CpuPerformanceSnapshot,
	gpu: GpuPerformanceSnapshot,
	ram: RamPerformanceSnapshot,
};

export type PlatformStatusSnapshot = {
	platformProfile: string | null,
	platformProfileChoices: string | null,
	platformProfileOnAc: string | null,
	platformProfileOnBattery: string | null,
	chargeControlEndThreshold: number | null,
	platformProfileLinkedEpp: boolean | null,
	lastError: string | null,
};

export type PowerStatusSnapshot = {
	activeProfile: string | null,
	profiles: string | null,
	performanceDegraded: string | null,
	lastError: string | null,
};

export type RamPerformanceSnapshot = {
	totalBytes: number | null,
	usedBytes: number | null,
	utilizationPercent: number | null,
	lastError: string | null,
};

export type ReadFanCurvesRequest = {
	profile: string,
};

export type ResetFanCurvesRequest = {
	profile: string,
};

export type ScsiStatusSnapshot = {
	enabled: boolean | null,
	mode: string | null,
	modeData: string | null,
	lastError: string | null,
};

export type SetAnimeBrightnessRequest = {
	level: number,
};

export type SetAnimeBuiltinsEnabledRequest = {
	enabled: boolean,
};

export type SetAnimeDisplayEnabledRequest = {
	enabled: boolean,
};

export type SetAnimeOffConditionRequest = {
	enabled: boolean,
};

export type SetArmouryValueRequest = {
	path: string,
	value: number,
};

export type SetAuraBrightnessRequest = {
	level: number,
};

export type SetAuraModeRequest = {
	mode: string,
};

export type SetBacklightRequest = {
	screenpadBrightness: number | null,
	screenpadGamma: number | null,
	syncScreenpadBrightness: boolean | null,
};

export type SetChargeLimitRequest = {
	percent: number,
};

export type SetFanCurvePointRequest = {
	temperature: number,
	pwm: number,
};

export type SetFanCurveRequest = {
	profile: string,
	fan: string,
	points: SetFanCurvePointRequest[],
	enabled: boolean,
};

export type SetFanCurvesEnabledRequest = {
	profile: string,
	enabled: boolean,
};

export type SetGpuModeRequest = {
	mode: string,
};

export type SetLedsBrightnessRequest = {
	level: string,
};

export type SetPlatformProfileRequest = {
	profile: string,
	ac?: boolean,
	battery?: boolean,
};

export type SetPowerProfileRequest = {
	profile: string,
};

export type SetScsiEnabledRequest = {
	enabled: boolean,
};

export type SetScsiModeRequest = {
	mode: number,
};

export type SetSlashBrightnessRequest = {
	brightness: number,
};

export type SetSlashEnabledRequest = {
	enabled: boolean,
};

export type SetSlashFlagRequest = {
	enabled: boolean,
};

export type SetSlashIntervalRequest = {
	interval: number,
};

export type SetSlashModeRequest = {
	mode: string,
};

export type SlashStatusSnapshot = {
	enabled: boolean | null,
	brightness: number | null,
	interval: number | null,
	mode: string | null,
	showOnBoot: boolean | null,
	showOnSleep: boolean | null,
	showOnShutdown: boolean | null,
	showOnBattery: boolean | null,
	showBatteryWarning: boolean | null,
	showOnLidClosed: boolean | null,
	lastError: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

